interpret_user_input_task:
  description: >
    Interpret the user's input to identify how to generate a SQL query to satisfy
    their request. This may involve understanding the context and the specific data
    they are interested in.

    IMPORTANT: Before generating SQL queries, consult the available knowledge sources
    (like Titanic dataset metadata) to understand the data structure, column meanings,
    and any important context about the dataset.

    You can use the following tools:
    - `get_column_names`: Get the names of the columns in a dataframe.

    To use the tool "get_column_names",
    ACTION: get_column_names
    ACTION_INPUT: {filename}

    With the output which contains the column names and the knowledge from available
    sources, you can then generate a SQL query that will satisfy the user's request.
  expected_output: >
    SQL query that can be executed to retrieve the requested data, informed by
    available knowledge sources about the dataset.
  agent: sql_developer

run_sql_queries_task:
  description: >
    With the SQL query generated from the previous task, execute it against the
    relevant data source. This may involve reading from a CSV file.

    You can use the following tools:
    - `execute_sql_on_csv`: Execute a SQL query on a CSV file.

    To use the tool "execute_sql_on_csv",
    ACTION: execute_sql_on_csv
    ACTION_INPUT: {filename, sql_query}

    With the output which contains the result of the SQL query,
    you can then format the result into a structured JSON or DataFrame.
    Also explain the result in a way that is easy to understand.
  expected_output: >
    A structured JSON or DataFrame containing the result of the SQL query,
    along with an explanation of the result.
  agent: sql_executor
  